/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentRouteImport } from './routes/talent'
import { Route as ReferRouteImport } from './routes/refer'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as CandidateRouteImport } from './routes/candidate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TalentIndexRouteImport } from './routes/talent.index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as TalentSearchRouteImport } from './routes/talent.search'
import { Route as TalentInsightsRouteImport } from './routes/talent.insights'
import { Route as TalentImportRouteImport } from './routes/talent.import'
import { Route as PortalLoginRouteImport } from './routes/portal.login'
import { Route as PortalEmployersRouteImport } from './routes/portal.employers'
import { Route as PortalAdminRouteImport } from './routes/portal.admin'
import { Route as CandidateProfileRouteImport } from './routes/candidate.profile'
import { Route as CandidateClaimRouteImport } from './routes/candidate.claim'
import { Route as TalentCandidatesProfileIdRouteImport } from './routes/talent.candidates.$profileId'
import { Route as PortalCandidatesApplicationIdRouteImport } from './routes/portal.candidates.$applicationId'

const TalentRoute = TalentRouteImport.update({
  id: '/talent',
  path: '/talent',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferRoute = ReferRouteImport.update({
  id: '/refer',
  path: '/refer',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateRoute = CandidateRouteImport.update({
  id: '/candidate',
  path: '/candidate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentIndexRoute = TalentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TalentRoute,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const TalentSearchRoute = TalentSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => TalentRoute,
} as any)
const TalentInsightsRoute = TalentInsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => TalentRoute,
} as any)
const TalentImportRoute = TalentImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => TalentRoute,
} as any)
const PortalLoginRoute = PortalLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PortalRoute,
} as any)
const PortalEmployersRoute = PortalEmployersRouteImport.update({
  id: '/employers',
  path: '/employers',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdminRoute = PortalAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => PortalRoute,
} as any)
const CandidateProfileRoute = CandidateProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CandidateRoute,
} as any)
const CandidateClaimRoute = CandidateClaimRouteImport.update({
  id: '/claim',
  path: '/claim',
  getParentRoute: () => CandidateRoute,
} as any)
const TalentCandidatesProfileIdRoute =
  TalentCandidatesProfileIdRouteImport.update({
    id: '/candidates/$profileId',
    path: '/candidates/$profileId',
    getParentRoute: () => TalentRoute,
  } as any)
const PortalCandidatesApplicationIdRoute =
  PortalCandidatesApplicationIdRouteImport.update({
    id: '/candidates/$applicationId',
    path: '/candidates/$applicationId',
    getParentRoute: () => PortalRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/refer': typeof ReferRoute
  '/talent': typeof TalentRouteWithChildren
  '/candidate/claim': typeof CandidateClaimRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/employers': typeof PortalEmployersRoute
  '/portal/login': typeof PortalLoginRoute
  '/talent/import': typeof TalentImportRoute
  '/talent/insights': typeof TalentInsightsRoute
  '/talent/search': typeof TalentSearchRoute
  '/portal/': typeof PortalIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/portal/candidates/$applicationId': typeof PortalCandidatesApplicationIdRoute
  '/talent/candidates/$profileId': typeof TalentCandidatesProfileIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/refer': typeof ReferRoute
  '/candidate/claim': typeof CandidateClaimRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/employers': typeof PortalEmployersRoute
  '/portal/login': typeof PortalLoginRoute
  '/talent/import': typeof TalentImportRoute
  '/talent/insights': typeof TalentInsightsRoute
  '/talent/search': typeof TalentSearchRoute
  '/portal': typeof PortalIndexRoute
  '/talent': typeof TalentIndexRoute
  '/portal/candidates/$applicationId': typeof PortalCandidatesApplicationIdRoute
  '/talent/candidates/$profileId': typeof TalentCandidatesProfileIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/candidate': typeof CandidateRouteWithChildren
  '/portal': typeof PortalRouteWithChildren
  '/refer': typeof ReferRoute
  '/talent': typeof TalentRouteWithChildren
  '/candidate/claim': typeof CandidateClaimRoute
  '/candidate/profile': typeof CandidateProfileRoute
  '/portal/admin': typeof PortalAdminRoute
  '/portal/employers': typeof PortalEmployersRoute
  '/portal/login': typeof PortalLoginRoute
  '/talent/import': typeof TalentImportRoute
  '/talent/insights': typeof TalentInsightsRoute
  '/talent/search': typeof TalentSearchRoute
  '/portal/': typeof PortalIndexRoute
  '/talent/': typeof TalentIndexRoute
  '/portal/candidates/$applicationId': typeof PortalCandidatesApplicationIdRoute
  '/talent/candidates/$profileId': typeof TalentCandidatesProfileIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/candidate'
    | '/portal'
    | '/refer'
    | '/talent'
    | '/candidate/claim'
    | '/candidate/profile'
    | '/portal/admin'
    | '/portal/employers'
    | '/portal/login'
    | '/talent/import'
    | '/talent/insights'
    | '/talent/search'
    | '/portal/'
    | '/talent/'
    | '/portal/candidates/$applicationId'
    | '/talent/candidates/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/candidate'
    | '/refer'
    | '/candidate/claim'
    | '/candidate/profile'
    | '/portal/admin'
    | '/portal/employers'
    | '/portal/login'
    | '/talent/import'
    | '/talent/insights'
    | '/talent/search'
    | '/portal'
    | '/talent'
    | '/portal/candidates/$applicationId'
    | '/talent/candidates/$profileId'
  id:
    | '__root__'
    | '/'
    | '/candidate'
    | '/portal'
    | '/refer'
    | '/talent'
    | '/candidate/claim'
    | '/candidate/profile'
    | '/portal/admin'
    | '/portal/employers'
    | '/portal/login'
    | '/talent/import'
    | '/talent/insights'
    | '/talent/search'
    | '/portal/'
    | '/talent/'
    | '/portal/candidates/$applicationId'
    | '/talent/candidates/$profileId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CandidateRoute: typeof CandidateRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  ReferRoute: typeof ReferRoute
  TalentRoute: typeof TalentRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talent': {
      id: '/talent'
      path: '/talent'
      fullPath: '/talent'
      preLoaderRoute: typeof TalentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refer': {
      id: '/refer'
      path: '/refer'
      fullPath: '/refer'
      preLoaderRoute: typeof ReferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate': {
      id: '/candidate'
      path: '/candidate'
      fullPath: '/candidate'
      preLoaderRoute: typeof CandidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talent/': {
      id: '/talent/'
      path: '/'
      fullPath: '/talent/'
      preLoaderRoute: typeof TalentIndexRouteImport
      parentRoute: typeof TalentRoute
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/talent/search': {
      id: '/talent/search'
      path: '/search'
      fullPath: '/talent/search'
      preLoaderRoute: typeof TalentSearchRouteImport
      parentRoute: typeof TalentRoute
    }
    '/talent/insights': {
      id: '/talent/insights'
      path: '/insights'
      fullPath: '/talent/insights'
      preLoaderRoute: typeof TalentInsightsRouteImport
      parentRoute: typeof TalentRoute
    }
    '/talent/import': {
      id: '/talent/import'
      path: '/import'
      fullPath: '/talent/import'
      preLoaderRoute: typeof TalentImportRouteImport
      parentRoute: typeof TalentRoute
    }
    '/portal/login': {
      id: '/portal/login'
      path: '/login'
      fullPath: '/portal/login'
      preLoaderRoute: typeof PortalLoginRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/employers': {
      id: '/portal/employers'
      path: '/employers'
      fullPath: '/portal/employers'
      preLoaderRoute: typeof PortalEmployersRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/admin': {
      id: '/portal/admin'
      path: '/admin'
      fullPath: '/portal/admin'
      preLoaderRoute: typeof PortalAdminRouteImport
      parentRoute: typeof PortalRoute
    }
    '/candidate/profile': {
      id: '/candidate/profile'
      path: '/profile'
      fullPath: '/candidate/profile'
      preLoaderRoute: typeof CandidateProfileRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/candidate/claim': {
      id: '/candidate/claim'
      path: '/claim'
      fullPath: '/candidate/claim'
      preLoaderRoute: typeof CandidateClaimRouteImport
      parentRoute: typeof CandidateRoute
    }
    '/talent/candidates/$profileId': {
      id: '/talent/candidates/$profileId'
      path: '/candidates/$profileId'
      fullPath: '/talent/candidates/$profileId'
      preLoaderRoute: typeof TalentCandidatesProfileIdRouteImport
      parentRoute: typeof TalentRoute
    }
    '/portal/candidates/$applicationId': {
      id: '/portal/candidates/$applicationId'
      path: '/candidates/$applicationId'
      fullPath: '/portal/candidates/$applicationId'
      preLoaderRoute: typeof PortalCandidatesApplicationIdRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface CandidateRouteChildren {
  CandidateClaimRoute: typeof CandidateClaimRoute
  CandidateProfileRoute: typeof CandidateProfileRoute
}

const CandidateRouteChildren: CandidateRouteChildren = {
  CandidateClaimRoute: CandidateClaimRoute,
  CandidateProfileRoute: CandidateProfileRoute,
}

const CandidateRouteWithChildren = CandidateRoute._addFileChildren(
  CandidateRouteChildren,
)

interface PortalRouteChildren {
  PortalAdminRoute: typeof PortalAdminRoute
  PortalEmployersRoute: typeof PortalEmployersRoute
  PortalLoginRoute: typeof PortalLoginRoute
  PortalIndexRoute: typeof PortalIndexRoute
  PortalCandidatesApplicationIdRoute: typeof PortalCandidatesApplicationIdRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdminRoute: PortalAdminRoute,
  PortalEmployersRoute: PortalEmployersRoute,
  PortalLoginRoute: PortalLoginRoute,
  PortalIndexRoute: PortalIndexRoute,
  PortalCandidatesApplicationIdRoute: PortalCandidatesApplicationIdRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

interface TalentRouteChildren {
  TalentImportRoute: typeof TalentImportRoute
  TalentInsightsRoute: typeof TalentInsightsRoute
  TalentSearchRoute: typeof TalentSearchRoute
  TalentIndexRoute: typeof TalentIndexRoute
  TalentCandidatesProfileIdRoute: typeof TalentCandidatesProfileIdRoute
}

const TalentRouteChildren: TalentRouteChildren = {
  TalentImportRoute: TalentImportRoute,
  TalentInsightsRoute: TalentInsightsRoute,
  TalentSearchRoute: TalentSearchRoute,
  TalentIndexRoute: TalentIndexRoute,
  TalentCandidatesProfileIdRoute: TalentCandidatesProfileIdRoute,
}

const TalentRouteWithChildren =
  TalentRoute._addFileChildren(TalentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CandidateRoute: CandidateRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  ReferRoute: ReferRoute,
  TalentRoute: TalentRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
